from tkinter import *
def calc():
    weight=float(e2.get())
    height=float(e3.get())
    res.set(weight/(height/10)**2)
app=Tk()
app.title("BMI CALULATOR")
frame=Frame(app)
frame.pack()
l1=Label(app,text="age")
l1.pack()
e1=Entry(app)
e1.pack()
l2=Label(app,text="enter your weight in kg")
l2.pack()
e2=Entry(app)
e2.pack()
l3=Label(app,text="enter your height in cm")
l3.pack()
e3=Entry(app)
e3.pack()
btn=Button(app,text="calculate",command=calc)
btn.pack()
res=StringVar()
res.set("result")
l4=Label(app,textvariable=res)
l4.pack()
app.mainloop()